version: '3'
services:
  mlflow:
    build: .
    container_name: mlflow
    ports:
      - 5000:5000
    environment:
      MLFLOW_DB_URI: mysql://${MLFLOW_DB_USER}:${MLFLOW_DB_PASSWORD}@${MLFLOW_DB_ENDPOINT}:${MLFLOW_DB_PORT}/mlflow
      MLFLOW_S3_URI: ${MLFLOW_S3_URI}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}